### ISSUE TITLE
How do I manage validatations of attributes with Storext?

### ISSUE THREAD

**Issue by catharinavas** [G5/storext#67]
I would like to do something like this:
![image](https://user-images.githubusercontent.com/17905364/79163633-be2caf80-7ddf-11ea-862f-5f29e7f9b316.png)
But I get this error on `group.save!` :
```
PG::UndefinedColumn: ERROR:  column groups.name does not exist
LINE 1: SELECT 1 AS one FROM "groups" WHERE "groups"."name" = $1 LIM...
```
How can I make it work?

Thank you for the help. I'm still trying to figure out how to work with JSONB columns...

**Comment by ramontayag** [comment]
Yes, I didn't expect that to work because the built-in Rails validations were made for normal columns. If all your records have the use for `name`, I suggest making it a normal column. If you're sure you want `name` to be a jsonb column, you will need to make your own validation:

```ruby
def validate_name_uniqueness
  arel = where("preferences ->> 'name' = '#{name}'")
  arel = arel.where.not(id: id) if self.persisted?
  return true if arel.empty?
  errors.add(:name, "must be unique")
end
```

[This gist](https://gist.github.com/mankind/1802dbb64fc24be33d434d593afd6221#file-rails-jsonb-queries-L22) has many query examples.

**Comment by catharinavas** [comment]
I will take a look there. Thank you!
